# Generated by Django 3.0 on 2019-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, default='/home/saltyclown/Desktop/Dell/hack2hire/static/img/grey-box.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, default='/home/saltyclown/Desktop/Dell/hack2hire/static/img/grey-box.png', upload_to=''),
        ),
    ]
