# Generated by Django 3.0 on 2019-12-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191212_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, default='/home/saltyclown/Desktop/Dell/hack2hire/static/img/grey-box.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, default='/home/saltyclown/Desktop/Dell/hack2hire/static/img/grey-box.png', null=True, upload_to=''),
        ),
    ]
