# Generated by Django 3.0 on 2019-12-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191212_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='selected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='recommended',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='selected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
