# Generated by Django 3.0 on 2019-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191214_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitedCount', models.PositiveIntegerField()),
                ('selectedCount', models.PositiveIntegerField()),
            ],
        ),
    ]
