# Generated by Django 3.0 on 2019-12-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='checkout',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
