# Generated by Django 3.0 on 2019-12-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_laptop_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraction',
            old_name='selectedCount',
            new_name='checkedoutCount',
        ),
    ]
