# Generated by Django 3.0 on 2019-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191216_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='recommended',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='selected',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='checkedoutCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='visitedCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
